spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:mysql://localhost:3316/inventory_service
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8082

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observation:
    key-values:
      application: product-service
  tracing:
    sampling:
      probability: 1