services:
  mysql:
    image: mysql:latest
    container_name: inventory-service-mysql
    ports:
      - "3316:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - inventory-service:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  inventory-service:
    driver: local